#!/usr/bin/env python3
"""
Spectra SDR — Customer Validation Script
=============================================
Run this after loading the bitstream to verify your SDR is working correctly.

Usage:
  # Via PCIe (after loading litepcie driver):
  sudo python3 validate_sdr.py

  # Via JTAG (no driver needed — requires openocd + litex_server running):
  litex_server --jtag --jtag-config openocd_xc7_ft2232.cfg &
  python3 validate_sdr.py --transport jtag

Requirements:
  pip install litex

The bitstream ships a LiteX CSR bridge. The script checks:
  - SoC identification string (confirms bitstream is loaded)
  - FPGA temperature and supply voltages (XADC)
  - Unique device DNA serial number
  - HyperRAM read/write (confirms 8 MB memory is working)
  - AD9364 product ID + SPI loopback (confirms RFIC is alive and SPI bus works)
  - AD9364 revision and key register readback
  - LED toggle (visual confirmation)
  - PCIe DMA status (PCIe transport only)
  - USB PHY detection (checks USB3320 ULPI device is visible on host)
"""

import os
import sys
import time
import struct
import random
import argparse

# ──────────────────────────────────────────────────────────────────────────────
# Colour helpers
# ──────────────────────────────────────────────────────────────────────────────

def _colour(code, text):
    if sys.stdout.isatty():
        return f"\033[{code}m{text}\033[0m"
    return text

PASS  = lambda t: _colour("32;1", t)
FAIL  = lambda t: _colour("31;1", t)
WARN  = lambda t: _colour("33;1", t)
HEAD  = lambda t: _colour("36;1", t)
BOLD  = lambda t: _colour("1",    t)

# ──────────────────────────────────────────────────────────────────────────────
# SPI helpers  (uses ad9364_spi_* CSRs generated by LiteX)
# ──────────────────────────────────────────────────────────────────────────────

# AD9364 SPI frame (24-bit):
#  [23]    R/~W  — 1 = read
#  [22:21] W[1:0] — 00 = 1-byte transfer
#  [20:8]  Address (13-bit, but AD9364 uses bits 12:0)
#  [7:0]   Data (ignored on read, written on write)

def _spi_read(bus, addr):
    """Perform a 24-bit SPI read of the AD9364 register at `addr`."""
    mosi_val = (1 << 23) | (addr << 8)          # R=1, W[1:0]=00, addr, data=0
    bus.regs.ad9364_spi_mosi.write(mosi_val)
    bus.regs.ad9364_spi_control.write((24 << 8) | 1)  # length=24, start=1
    timeout = time.time() + 0.1
    while not (bus.regs.ad9364_spi_status.read() & 1):
        if time.time() > timeout:
            raise TimeoutError("SPI transfer timed out")
        time.sleep(0.001)
    return bus.regs.ad9364_spi_miso.read() & 0xFF


def _spi_write(bus, addr, data):
    """Perform a 24-bit SPI write of `data` to the AD9364 register at `addr`."""
    mosi_val = (0 << 23) | (addr << 8) | (data & 0xFF)  # R=0
    bus.regs.ad9364_spi_mosi.write(mosi_val)
    bus.regs.ad9364_spi_control.write((24 << 8) | 1)
    timeout = time.time() + 0.1
    while not (bus.regs.ad9364_spi_status.read() & 1):
        if time.time() > timeout:
            raise TimeoutError("SPI transfer timed out")
        time.sleep(0.001)

# ──────────────────────────────────────────────────────────────────────────────
# Individual test functions
# ──────────────────────────────────────────────────────────────────────────────

def check_pcie_device():
    """Check that the PCIe device node exists (driver loaded)."""
    node = "/dev/litepcie0"
    exists = os.path.exists(node)
    return exists, node


def test_xadc(bus):
    """Read FPGA internal sensors via XADC."""
    raw_temp   = bus.regs.xadc_temperature.read()
    raw_vccint = bus.regs.xadc_vccint.read()
    raw_vccaux = bus.regs.xadc_vccaux.read()
    raw_vccbram= bus.regs.xadc_vccbram.read()

    temp    = raw_temp   * 503.975 / 4096 - 273.15
    vccint  = raw_vccint  * 3 / 4096
    vccaux  = raw_vccaux  * 3 / 4096
    vccbram = raw_vccbram * 3 / 4096

    results = {
        "temp_c":   temp,
        "vccint_v": vccint,
        "vccaux_v": vccaux,
        "vccbram_v":vccbram,
    }

    # Sanity bounds
    ok = (
        0 < temp < 85 and
        0.92 < vccint  < 1.08 and   # nominal 1.0V ±8%
        1.70 < vccaux  < 1.90 and   # nominal 1.8V ±6%
        0.92 < vccbram < 1.08       # nominal 1.0V ±8%
    )
    return ok, results


def test_dna(bus):
    """Read the unique FPGA DNA identifier."""
    dna_hi = bus.regs.dna_id.read()   # LiteX packs 64-bit as two 32-bit regs
    # RemoteClient automatically handles multi-word: returns 64-bit int
    dna = dna_hi
    return True, dna


def test_ad9364_spi(bus):
    """Ping the AD9364 RFIC by reading its Product ID register (0x037 → 0x0A)."""
    PRODUCT_ID_REG = 0x037
    EXPECTED_ID    = 0x0A   # AD9364 product ID

    try:
        chip_id = _spi_read(bus, PRODUCT_ID_REG)
    except TimeoutError as e:
        return False, {"error": str(e), "chip_id": None}

    ok = (chip_id == EXPECTED_ID)
    return ok, {"chip_id": chip_id, "expected": EXPECTED_ID}


def test_ad9364_reset_cycle(bus):
    """Assert and deassert AD9364 reset, then re-read product ID."""
    # PHY control bit 0 = rst_n (active-low reset).
    bus.regs.ad9364_phy_control.write(0x00)   # assert reset (rst_n=0)
    time.sleep(0.01)
    bus.regs.ad9364_phy_control.write(0x01)   # deassert reset (rst_n=1)
    time.sleep(0.05)                           # wait for RFIC boot

    ok, info = test_ad9364_spi(bus)
    return ok, info


def test_soc_ident(bus):
    """Read the LiteX SoC identification string."""
    ident = ""
    try:
        # LiteX identifier is a CSR memory — read byte by byte
        i = 0
        while True:
            val = bus.read(bus.mems.identifier_mem.base + i * 4)
            if val == 0:
                break
            ident += chr(val & 0xFF)
            i += 1
            if i > 128:  # safety limit
                break
    except Exception:
        # Fallback: some RemoteClient versions expose it differently
        try:
            ident = bus.identifier
        except Exception:
            pass
    ok = len(ident) > 0
    return ok, ident


def test_hyperram(bus, base_addr=0x40000000, test_size=256):
    """Write and read back test patterns to HyperRAM."""
    # Generate deterministic test patterns
    patterns = [
        ("Walking ones",  [1 << (i % 32) for i in range(test_size // 4)]),
        ("Walking zeros", [~(1 << (i % 32)) & 0xFFFFFFFF for i in range(test_size // 4)]),
        ("Random",        [random.randint(0, 0xFFFFFFFF) for _ in range(test_size // 4)]),
    ]
    results = {}
    all_ok = True
    for name, data in patterns:
        # Write
        for i, word in enumerate(data):
            bus.write(base_addr + i * 4, word)
        # Read back and verify
        mismatches = 0
        for i, expected in enumerate(data):
            got = bus.read(base_addr + i * 4)
            if got != expected:
                mismatches += 1
        ok = (mismatches == 0)
        results[name] = {"ok": ok, "mismatches": mismatches, "words": len(data)}
        if not ok:
            all_ok = False
    return all_ok, results


def test_ad9364_spi_loopback(bus):
    """Write and readback AD9364 scratch register to verify SPI bus integrity."""
    # AD9364 has a scratch pad register at 0x00A that can be written and read back.
    SCRATCH_REG = 0x00A
    test_values = [0x55, 0xAA, 0x0F, 0xF0, 0x00, 0xFF]
    results = []
    all_ok = True
    for val in test_values:
        try:
            _spi_write(bus, SCRATCH_REG, val)
            readback = _spi_read(bus, SCRATCH_REG)
            ok = (readback == val)
            results.append({"wrote": val, "read": readback, "ok": ok})
            if not ok:
                all_ok = False
        except TimeoutError as e:
            results.append({"wrote": val, "read": None, "ok": False, "error": str(e)})
            all_ok = False
    return all_ok, results


def test_ad9364_revision(bus):
    """Read AD9364 product ID and revision registers."""
    # 0x037 = Product ID (0x0A for AD9364)
    # 0x005 = Device revision
    try:
        product_id = _spi_read(bus, 0x037)
        revision   = _spi_read(bus, 0x005)
    except TimeoutError as e:
        return False, {"error": str(e)}

    # Identify the chip variant from product ID
    chip_names = {0x0A: "AD9364", 0x08: "AD9361", 0x06: "AD9363"}
    chip_name = chip_names.get(product_id, f"Unknown (0x{product_id:02X})")

    ok = product_id in (0x0A, 0x08, 0x06)  # any AD936x is valid
    return ok, {
        "product_id": product_id,
        "chip": chip_name,
        "revision": revision,
    }


def test_led_toggle(bus):
    """Toggle LEDs to provide visual confirmation."""
    try:
        # LedChaser exposes an 'out' CSR — write directly to override
        original = bus.regs.leds_out.read()
        # Blink pattern: all on, all off, restore
        bus.regs.leds_out.write(0x03)  # both LEDs on
        time.sleep(0.2)
        bus.regs.leds_out.write(0x00)  # both LEDs off
        time.sleep(0.2)
        bus.regs.leds_out.write(0x03)  # both LEDs on
        time.sleep(0.2)
        bus.regs.leds_out.write(original)  # restore
        return True, "LEDs toggled (check board visually)"
    except Exception as e:
        return False, str(e)


def test_usb_device():
    """Check if the Spectra SDR USB device (VID:1209 PID:5380) is visible on the host."""
    USB_VID = 0x1209
    USB_PID = 0x5380
    try:
        import usb.core
        dev = usb.core.find(idVendor=USB_VID, idProduct=USB_PID)
        if dev is None:
            return False, {"found": False, "reason": "not detected on USB bus"}
        serial = ""
        try:
            import usb.util
            serial = usb.util.get_string(dev, dev.iSerialNumber) if dev.iSerialNumber else ""
        except Exception:
            pass
        return True, {
            "found": True,
            "bus": dev.bus,
            "address": dev.address,
            "serial": serial,
        }
    except ImportError:
        return None, {"found": None, "reason": "pyusb not installed (pip install pyusb)"}


def test_pcie_dma_idle(bus):
    """Confirm DMA engine is present and idle (no stray enables)."""
    writer_en = bus.regs.pcie_dma0_writer_enable.read()
    reader_en = bus.regs.pcie_dma0_reader_enable.read()
    # Both should be 0 before we start anything
    ok = (writer_en == 0) and (reader_en == 0)
    return ok, {"writer_enable": writer_en, "reader_enable": reader_en}


# ──────────────────────────────────────────────────────────────────────────────
# Main
# ──────────────────────────────────────────────────────────────────────────────

def banner():
    print()
    print(HEAD("╔══════════════════════════════════════════════════╗"))
    print(HEAD("║         Spectra SDR — Hardware Validation          ║"))
    print(HEAD("╚══════════════════════════════════════════════════╝"))
    print()


def result_line(label, ok, detail=""):
    status = PASS("PASS") if ok else FAIL("FAIL")
    detail_str = f"  {detail}" if detail else ""
    print(f"  [{status}]  {label}{detail_str}")


def main():
    banner()

    parser = argparse.ArgumentParser(
        description="Spectra SDR hardware validation script",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--transport", choices=["pcie", "jtag"], default="pcie",
        help="How to reach the LiteX CSR bridge (default: pcie). "
             "Use 'jtag' if you haven't loaded the kernel driver yet.",
    )
    parser.add_argument(
        "--csr-csv", default=None,
        help="Path to csr.csv (default: auto-detect from build directory).",
    )
    parser.add_argument(
        "--host", default="localhost",
        help="litex_server host (default: localhost).",
    )
    parser.add_argument(
        "--port", default=1234, type=int,
        help="litex_server port (default: 1234).",
    )
    parser.add_argument(
        "--skip-reset", action="store_true",
        help="Skip the AD9364 reset cycle (useful if RFIC is already initialised).",
    )
    args = parser.parse_args()

    # ── Locate csr.csv ─────────────────────────────────────────────────────
    if args.csr_csv:
        csr_csv = args.csr_csv
    else:
        # Default: look next to this script, then in the build tree.
        script_dir = os.path.dirname(os.path.abspath(__file__))
        candidates = [
            os.path.join(script_dir, "csr.csv"),
            os.path.join(script_dir, "build", "spectra_platform", "csr.csv"),
        ]
        csr_csv = next((p for p in candidates if os.path.exists(p)), None)
        if csr_csv is None:
            print(FAIL("ERROR") + " Cannot find csr.csv. Pass --csr-csv <path>.")
            sys.exit(1)

    print(BOLD("Configuration"))
    print(f"  Transport : {args.transport.upper()}")
    print(f"  CSR CSV   : {csr_csv}")
    print()

    failures = []

    # ── Step 1: PCIe device node (PCIe transport only) ─────────────────────
    if args.transport == "pcie":
        print(BOLD("Step 1 — PCIe enumeration"))
        ok, node = check_pcie_device()
        result_line("/dev/litepcie0 present", ok, node if ok else "not found — load the litepcie driver")
        if not ok:
            failures.append("PCIe device node missing")
        print()
    else:
        print(BOLD("Step 1 — PCIe enumeration"))
        print(f"  [----]  Skipped (transport=jtag)")
        print()

    # ── Connect RemoteClient ───────────────────────────────────────────────
    print(BOLD("Connecting to LiteX CSR bridge …"))
    try:
        from litex import RemoteClient
        bus = RemoteClient(host=args.host, port=args.port, csr_csv=csr_csv)
        bus.open()
        print(f"  Connected  ({args.host}:{args.port})")
    except Exception as e:
        print(FAIL(f"  FAIL — cannot connect: {e}"))
        if args.transport == "jtag":
            print("  Hint: run  litex_server --jtag --jtag-config openocd_xc7_ft2232.cfg  first.")
        else:
            print("  Hint: run  litex_server --pcie  (or use --transport jtag for JTAG access).")
        sys.exit(1)
    print()

    # ── Step 2: SoC identification ──────────────────────────────────────────
    print(BOLD("Step 2 — SoC identification"))
    try:
        ok, ident = test_soc_ident(bus)
        result_line("SoC ident string", ok, ident if ok else "empty or unreadable")
        if not ok:
            failures.append("SoC ident string empty")
    except Exception as e:
        result_line("SoC ident", False, str(e))
        failures.append(f"SoC ident error: {e}")
    print()

    # ── Step 3: XADC — FPGA temperature and voltages ──────────────────────
    print(BOLD("Step 3 — FPGA health (XADC)"))
    try:
        ok, xadc = test_xadc(bus)
        result_line("Temperature in range (0–85 °C)",    0 < xadc["temp_c"] < 85,
                    f"{xadc['temp_c']:.1f} °C")
        result_line("VCCINT  nominal 1.0 V  (±8%)",      0.92 < xadc["vccint_v"]  < 1.08,
                    f"{xadc['vccint_v']:.3f} V")
        result_line("VCCAUX  nominal 1.8 V  (±6%)",      1.70 < xadc["vccaux_v"]  < 1.90,
                    f"{xadc['vccaux_v']:.3f} V")
        result_line("VCCBRAM nominal 1.0 V  (±8%)",      0.92 < xadc["vccbram_v"] < 1.08,
                    f"{xadc['vccbram_v']:.3f} V")
        if not ok:
            failures.append("XADC readings out of range")
    except Exception as e:
        result_line("XADC read", False, str(e))
        failures.append(f"XADC error: {e}")
    print()

    # ── Step 4: DNA — unique device serial ────────────────────────────────
    print(BOLD("Step 4 — Device DNA (unique serial)"))
    try:
        ok, dna = test_dna(bus)
        dna_str = f"0x{dna:016X}"
        is_nonzero = dna != 0
        result_line("DNA ID readable and non-zero", is_nonzero, dna_str)
        if not is_nonzero:
            failures.append("DNA ID read as zero")
    except Exception as e:
        result_line("DNA read", False, str(e))
        failures.append(f"DNA error: {e}")
    print()

    # ── Step 5: HyperRAM ────────────────────────────────────────────────────
    print(BOLD("Step 5 — HyperRAM (8 MB)"))
    try:
        ok, ram_results = test_hyperram(bus)
        for name, info in ram_results.items():
            result_line(f"{name} pattern ({info['words']} words)", info["ok"],
                        f"{info['mismatches']} mismatches" if not info["ok"] else "OK")
        if not ok:
            failures.append("HyperRAM read/write failed")
    except Exception as e:
        result_line("HyperRAM test", False, str(e))
        failures.append(f"HyperRAM error: {e}")
    print()

    # ── Step 6: AD9364 reset + product ID ─────────────────────────────────
    print(BOLD("Step 6 — AD9364 RFIC (SPI ping)"))
    try:
        if args.skip_reset:
            ok, info = test_ad9364_spi(bus)
            label = "Product ID (0x037 → 0x0A), no reset"
        else:
            ok, info = test_ad9364_reset_cycle(bus)
            label = "Product ID (0x037 → 0x0A), after reset"

        if info.get("chip_id") is not None:
            detail = f"got 0x{info['chip_id']:02X}, expected 0x{info['expected']:02X}"
        else:
            detail = info.get("error", "")
        result_line(label, ok, detail)
        if not ok:
            failures.append("AD9364 SPI ping failed")
    except Exception as e:
        result_line("AD9364 SPI", False, str(e))
        failures.append(f"AD9364 error: {e}")
    print()

    # ── Step 7: AD9364 chip identification ───────────────────────────────
    print(BOLD("Step 7 — AD9364 chip identification"))
    try:
        ok, rev_info = test_ad9364_revision(bus)
        if "error" not in rev_info:
            result_line("Chip variant", ok,
                        f"{rev_info['chip']} (ID=0x{rev_info['product_id']:02X}, rev=0x{rev_info['revision']:02X})")
        else:
            result_line("Chip identification", False, rev_info["error"])
        if not ok:
            failures.append("AD9364 chip identification failed")
    except Exception as e:
        result_line("AD9364 revision", False, str(e))
        failures.append(f"AD9364 revision error: {e}")
    print()

    # ── Step 8: AD9364 SPI bus integrity ──────────────────────────────────
    print(BOLD("Step 8 — AD9364 SPI loopback (scratch register)"))
    try:
        ok, spi_results = test_ad9364_spi_loopback(bus)
        passed = sum(1 for r in spi_results if r["ok"])
        total = len(spi_results)
        result_line(f"SPI write/readback ({passed}/{total} patterns)", ok,
                    "all matched" if ok else "mismatch detected")
        if not ok:
            for r in spi_results:
                if not r["ok"]:
                    detail = f"wrote 0x{r['wrote']:02X}, read 0x{r['read']:02X}" if r["read"] is not None else r.get("error", "")
                    print(f"           {FAIL('MISMATCH')}  {detail}")
            failures.append("AD9364 SPI loopback failed")
    except Exception as e:
        result_line("SPI loopback", False, str(e))
        failures.append(f"SPI loopback error: {e}")
    print()

    # ── Step 9: LED toggle ────────────────────────────────────────────────
    print(BOLD("Step 9 — LED toggle (visual check)"))
    try:
        ok, led_detail = test_led_toggle(bus)
        result_line("LED blink", ok, led_detail)
        if not ok:
            failures.append(f"LED toggle failed: {led_detail}")
    except Exception as e:
        result_line("LED toggle", False, str(e))
        failures.append(f"LED error: {e}")
    print()

    # ── Step 10: PCIe DMA (PCIe transport only) ───────────────────────────
    if args.transport == "pcie":
        print(BOLD("Step 10 — PCIe DMA engine"))
        try:
            ok, dma = test_pcie_dma_idle(bus)
            result_line("DMA writer idle (enable=0)", dma["writer_enable"] == 0,
                        f"writer_enable={dma['writer_enable']}")
            result_line("DMA reader idle (enable=0)", dma["reader_enable"] == 0,
                        f"reader_enable={dma['reader_enable']}")
            if not ok:
                failures.append("DMA not idle — unexpected state")
        except Exception as e:
            result_line("PCIe DMA read", False, str(e))
            failures.append(f"DMA error: {e}")
        print()
    else:
        print(BOLD("Step 10 — PCIe DMA engine"))
        print("  [----]  Skipped (transport=jtag)")
        print()

    bus.close()

    # ── Step 11: USB device detection ─────────────────────────────────────
    print(BOLD("Step 11 — USB device (VID:1209 PID:5380)"))
    ok, usb_info = test_usb_device()
    if ok is None:
        print(f"  [----]  Skipped ({usb_info['reason']})")
    elif ok:
        detail = f"bus {usb_info['bus']} addr {usb_info['address']}"
        if usb_info.get("serial"):
            detail += f", serial {usb_info['serial']}"
        result_line("USB device detected", True, detail)
    else:
        result_line("USB device detected", False, usb_info.get("reason", "not found"))
        # USB is optional — don't add to failures, just warn
        print(f"           {WARN('NOTE')}  USB is optional if using PCIe. "
              "Check USB cable if you expect USB connectivity.")
    print()

    # ── Summary ────────────────────────────────────────────────────────────
    print(HEAD("══════════════════════════════════════════════════════"))
    if not failures:
        print(PASS("  ALL TESTS PASSED — your Spectra SDR is ready."))
    else:
        print(FAIL(f"  {len(failures)} TEST(S) FAILED:"))
        for f in failures:
            print(f"    • {f}")
    print(HEAD("══════════════════════════════════════════════════════"))
    print()

    sys.exit(0 if not failures else 1)


if __name__ == "__main__":
    main()
