#!/usr/bin/env python3
"""
Spectra SDR — Customer Validation Script
=============================================
Run this after loading the bitstream to verify your SDR is working correctly.

Usage:
  # Via PCIe (after loading litepcie driver):
  sudo python3 validate_sdr.py

  # Via JTAG (no driver needed — requires openocd + litex_server running):
  litex_server --jtag --jtag-config openocd_xc7_ft2232.cfg &
  python3 validate_sdr.py --transport jtag

Requirements:
  pip install litex

The bitstream ships a LiteX CSR bridge. The script checks:
  - PCIe and USB interface detection (lspci, device node, lsusb)
  - SoC identification string (confirms bitstream is loaded)
  - FPGA temperature and supply voltages (XADC)
  - Unique device DNA serial number
  - HyperRAM read/write (confirms 8 MB memory is working)
  - AD9364 product ID + SPI loopback (confirms RFIC is alive and SPI bus works)
  - AD9364 revision and key register readback
  - LED toggle (visual confirmation)
  - PCIe DMA status (PCIe transport only)
  - USB EP3 control-plane bridge (READ32/WRITE32 over raw USB bulk transfers,
    independent of the --transport bus above; runs whenever a USB device is
    detected. Requires pyusb: pip install pyusb)
"""

import os
import sys
import time
import struct
import random
import argparse
import subprocess

# ──────────────────────────────────────────────────────────────────────────────
# Colour helpers
# ──────────────────────────────────────────────────────────────────────────────

def _colour(code, text):
    if sys.stdout.isatty():
        return f"\033[{code}m{text}\033[0m"
    return text

PASS  = lambda t: _colour("32;1", t)
FAIL  = lambda t: _colour("31;1", t)
WARN  = lambda t: _colour("33;1", t)
HEAD  = lambda t: _colour("36;1", t)
BOLD  = lambda t: _colour("1",    t)

# ──────────────────────────────────────────────────────────────────────────────
# SPI helpers  (uses ad9364_spi_* CSRs generated by LiteX)
# ──────────────────────────────────────────────────────────────────────────────

# AD9364 SPI frame (24-bit):
#  [23]    R/~W  — 1 = read
#  [22:21] W[1:0] — 00 = 1-byte transfer
#  [20:8]  Address (13-bit, but AD9364 uses bits 12:0)
#  [7:0]   Data (ignored on read, written on write)

def _spi_read(bus, addr):
    """Perform a 24-bit SPI read of the AD9364 register at `addr`."""
    mosi_val = (1 << 23) | (addr << 8)          # R=1, W[1:0]=00, addr, data=0
    bus.regs.ad9364_spi_mosi.write(mosi_val)
    bus.regs.ad9364_spi_control.write((24 << 8) | 1)  # length=24, start=1
    timeout = time.time() + 0.1
    while not (bus.regs.ad9364_spi_status.read() & 1):
        if time.time() > timeout:
            raise TimeoutError("SPI transfer timed out")
        time.sleep(0.001)
    return bus.regs.ad9364_spi_miso.read() & 0xFF


def _spi_write(bus, addr, data):
    """Perform a 24-bit SPI write of `data` to the AD9364 register at `addr`."""
    mosi_val = (0 << 23) | (addr << 8) | (data & 0xFF)  # R=0
    bus.regs.ad9364_spi_mosi.write(mosi_val)
    bus.regs.ad9364_spi_control.write((24 << 8) | 1)
    timeout = time.time() + 0.1
    while not (bus.regs.ad9364_spi_status.read() & 1):
        if time.time() > timeout:
            raise TimeoutError("SPI transfer timed out")
        time.sleep(0.001)

# ──────────────────────────────────────────────────────────────────────────────
# USB EP3 control-plane helpers
#
# Completely independent of RemoteClient/litex_server above — these talk
# directly to raw USB bulk endpoints 0x03 (OUT, command) / 0x83 (IN,
# response) using the 12-byte command / 8-byte response frames implemented
# by USBWishboneBridge + usb_iq_device.py's EP3 endpoints. Register
# addresses are looked up from the already-connected `bus` (RemoteClient)
# object's parsed csr.csv — same address map, two independent physical
# paths to it.
# ──────────────────────────────────────────────────────────────────────────────

USB_EP3_OUT = 0x03
USB_EP3_IN  = 0x83
USB_EP3_TIMEOUT_MS = 1000

USB_OP_READ32  = 0x01
USB_OP_WRITE32 = 0x02

USB_STATUS_OK         = 0x00
USB_STATUS_BUS_ERROR  = 0x01
USB_STATUS_BAD_OPCODE = 0x02

USB_STATUS_NAMES = {
    USB_STATUS_OK:         "OK",
    USB_STATUS_BUS_ERROR:  "BUS_ERROR",
    USB_STATUS_BAD_OPCODE: "BAD_OPCODE",
}


def _usb_ep3_open():
    """Open the Spectra SDR USB device and claim its interface for EP3 access."""
    import usb.core
    import usb.util
    dev = usb.core.find(idVendor=0x1209, idProduct=0x5380)
    if dev is None:
        raise RuntimeError("Spectra SDR USB device not found")
    try:
        if dev.is_kernel_driver_active(0):
            dev.detach_kernel_driver(0)
    except (NotImplementedError, usb.core.USBError):
        pass  # platform doesn't need/support detach
    dev.set_configuration()
    usb.util.claim_interface(dev, 0)
    return dev


def _usb_ep3_close(dev):
    import usb.util
    try:
        usb.util.release_interface(dev, 0)
    except Exception:
        pass


def _usb_ep3_transact(dev, opcode, addr, wdata=0):
    """Send one 12-byte EP3 command frame, return (status, rdata) from the 8-byte response."""
    cmd = struct.pack("<BxxxII", opcode, addr & 0xFFFFFFFF, wdata & 0xFFFFFFFF)
    dev.write(USB_EP3_OUT, cmd, timeout=USB_EP3_TIMEOUT_MS)
    resp = dev.read(USB_EP3_IN, 8, timeout=USB_EP3_TIMEOUT_MS)
    status, rdata = struct.unpack("<II", bytes(resp))
    return status, rdata


def usb_ep3_read32(dev, addr):
    status, rdata = _usb_ep3_transact(dev, USB_OP_READ32, addr)
    if status != USB_STATUS_OK:
        raise IOError(f"EP3 READ32 @0x{addr:08x} -> {USB_STATUS_NAMES.get(status, hex(status))}")
    return rdata


def usb_ep3_write32(dev, addr, data):
    status, _ = _usb_ep3_transact(dev, USB_OP_WRITE32, addr, data)
    if status != USB_STATUS_OK:
        raise IOError(f"EP3 WRITE32 @0x{addr:08x} -> {USB_STATUS_NAMES.get(status, hex(status))}")


def _usb_read_csr(dev, reg):
    """Read a (possibly multi-word) CSR entirely via EP3, reconstructing it
    the same MSB-first way CSRRegister.read() does over RemoteClient, so the
    two paths are directly comparable."""
    value = 0
    for i in range(reg.length):
        word = usb_ep3_read32(dev, reg.addr + i * 4)
        value = (value << reg.data_width) | word
    return value


def _usb_spi_read(dev, spi_addrs, spi_reg_addr):
    """AD9364 SPI read via raw USB EP3 register pokes — same sequence as
    _spi_read() above, but every step goes over USB bulk transfers instead
    of RemoteClient."""
    mosi_val = (1 << 23) | (spi_reg_addr << 8)
    usb_ep3_write32(dev, spi_addrs["mosi"], mosi_val)
    usb_ep3_write32(dev, spi_addrs["control"], (24 << 8) | 1)
    timeout = time.time() + 0.1
    while not (usb_ep3_read32(dev, spi_addrs["status"]) & 1):
        if time.time() > timeout:
            raise TimeoutError("USB EP3 SPI transfer timed out")
        time.sleep(0.001)
    return usb_ep3_read32(dev, spi_addrs["miso"]) & 0xFF


# ──────────────────────────────────────────────────────────────────────────────
# Individual test functions
# ──────────────────────────────────────────────────────────────────────────────

def check_pcie_device():
    """Check that the PCIe device node exists (driver loaded)."""
    for node in ["/dev/spectra0", "/dev/litepcie0"]:
        if os.path.exists(node):
            return True, node
    return False, None


def detect_pcie_bus():
    """Check if the Spectra SDR is visible on the PCIe bus via lspci."""
    try:
        out = subprocess.check_output(["lspci", "-nn"], text=True, stderr=subprocess.DEVNULL)
        for line in out.splitlines():
            if "7050" in line.lower() or "xilinx" in line.lower():
                return True, line.strip()
        return False, None
    except (FileNotFoundError, subprocess.CalledProcessError):
        return None, None  # lspci not available


def detect_usb_device():
    """Check if the Spectra SDR USB device (VID:1209 PID:5380) is on the bus."""
    # Try lsusb first (no python deps)
    try:
        out = subprocess.check_output(["lsusb"], text=True, stderr=subprocess.DEVNULL)
        for line in out.splitlines():
            if "1209:5380" in line:
                return True, line.strip()
        return False, None
    except (FileNotFoundError, subprocess.CalledProcessError):
        pass
    # Fallback to pyusb
    try:
        import usb.core
        import usb.util
        dev = usb.core.find(idVendor=0x1209, idProduct=0x5380)
        if dev is None:
            return False, None
        serial = ""
        try:
            serial = usb.util.get_string(dev, dev.iSerialNumber) if dev.iSerialNumber else ""
        except Exception:
            pass
        info = f"Bus {dev.bus:03d} Device {dev.address:03d}: ID 1209:5380 Spectra SDR"
        if serial:
            info += f" (serial: {serial})"
        return True, info
    except ImportError:
        return None, None  # neither lsusb nor pyusb


def test_xadc(bus):
    """Read FPGA internal sensors via XADC."""
    raw_temp   = bus.regs.xadc_temperature.read()
    raw_vccint = bus.regs.xadc_vccint.read()
    raw_vccaux = bus.regs.xadc_vccaux.read()
    raw_vccbram= bus.regs.xadc_vccbram.read()

    temp    = raw_temp   * 503.975 / 4096 - 273.15
    vccint  = raw_vccint  * 3 / 4096
    vccaux  = raw_vccaux  * 3 / 4096
    vccbram = raw_vccbram * 3 / 4096

    results = {
        "temp_c":   temp,
        "vccint_v": vccint,
        "vccaux_v": vccaux,
        "vccbram_v":vccbram,
    }

    # Sanity bounds
    ok = (
        0 < temp < 85 and
        0.92 < vccint  < 1.08 and   # nominal 1.0V ±8%
        1.70 < vccaux  < 1.90 and   # nominal 1.8V ±6%
        0.92 < vccbram < 1.08       # nominal 1.0V ±8%
    )
    return ok, results


def test_dna(bus):
    """Read the unique FPGA DNA identifier."""
    dna_hi = bus.regs.dna_id.read()   # LiteX packs 64-bit as two 32-bit regs
    # RemoteClient automatically handles multi-word: returns 64-bit int
    dna = dna_hi
    return True, dna


def test_ad9364_spi(bus):
    """Ping the AD9364 RFIC by reading its Product ID register (0x037 → 0x0A)."""
    PRODUCT_ID_REG = 0x037
    EXPECTED_ID    = 0x0A   # AD9364 product ID

    try:
        chip_id = _spi_read(bus, PRODUCT_ID_REG)
    except TimeoutError as e:
        return False, {"error": str(e), "chip_id": None}

    ok = (chip_id == EXPECTED_ID)
    return ok, {"chip_id": chip_id, "expected": EXPECTED_ID}


def test_ad9364_reset_cycle(bus):
    """Assert and deassert AD9364 reset (FPGA pin C14 / RESETB), then re-read product ID."""
    # ad9364_reset is a dedicated register: it self-releases once the sys
    # PLL locks (no software involvement needed on initial power-up), and
    # reads back the live pin state at all times. This test just drives an
    # explicit reset pulse on top of that.
    bus.regs.ad9364_reset.write(0)   # assert reset (rst_n=0)
    time.sleep(0.01)
    bus.regs.ad9364_reset.write(1)   # deassert reset (rst_n=1)
    time.sleep(0.05)                           # wait for RFIC boot

    ok, info = test_ad9364_spi(bus)
    return ok, info


def test_soc_ident(bus):
    """Read the LiteX SoC identification string."""
    ident = ""
    try:
        # LiteX identifier is a CSR memory — read byte by byte
        i = 0
        while True:
            val = bus.read(bus.mems.identifier_mem.base + i * 4)
            if val == 0:
                break
            ident += chr(val & 0xFF)
            i += 1
            if i > 128:  # safety limit
                break
    except Exception:
        # Fallback: some RemoteClient versions expose it differently
        try:
            ident = bus.identifier
        except Exception:
            pass
    ok = len(ident) > 0
    return ok, ident


def test_hyperram(bus, base_addr=0x40000000, test_size=256):
    """Write and read back test patterns to HyperRAM."""
    # Generate deterministic test patterns
    patterns = [
        ("Walking ones",  [1 << (i % 32) for i in range(test_size // 4)]),
        ("Walking zeros", [~(1 << (i % 32)) & 0xFFFFFFFF for i in range(test_size // 4)]),
        ("Random",        [random.randint(0, 0xFFFFFFFF) for _ in range(test_size // 4)]),
    ]
    results = {}
    all_ok = True
    for name, data in patterns:
        # Write
        for i, word in enumerate(data):
            bus.write(base_addr + i * 4, word)
        # Read back and verify
        mismatches = 0
        for i, expected in enumerate(data):
            got = bus.read(base_addr + i * 4)
            if got != expected:
                mismatches += 1
        ok = (mismatches == 0)
        results[name] = {"ok": ok, "mismatches": mismatches, "words": len(data)}
        if not ok:
            all_ok = False
    return all_ok, results


def test_ad9364_spi_loopback(bus):
    """Write and readback AD9364 scratch register to verify SPI bus integrity."""
    # AD9364 has a scratch pad register at 0x00A that can be written and read back.
    SCRATCH_REG = 0x00A
    test_values = [0x55, 0xAA, 0x0F, 0xF0, 0x00, 0xFF]
    results = []
    all_ok = True
    for val in test_values:
        try:
            _spi_write(bus, SCRATCH_REG, val)
            readback = _spi_read(bus, SCRATCH_REG)
            ok = (readback == val)
            results.append({"wrote": val, "read": readback, "ok": ok})
            if not ok:
                all_ok = False
        except TimeoutError as e:
            results.append({"wrote": val, "read": None, "ok": False, "error": str(e)})
            all_ok = False
    return all_ok, results


def test_ad9364_revision(bus):
    """Read AD9364 product ID and revision registers."""
    # 0x037 = Product ID (0x0A for AD9364)
    # 0x005 = Device revision
    try:
        product_id = _spi_read(bus, 0x037)
        revision   = _spi_read(bus, 0x005)
    except TimeoutError as e:
        return False, {"error": str(e)}

    # Identify the chip variant from product ID
    chip_names = {0x0A: "AD9364", 0x08: "AD9361", 0x06: "AD9363"}
    chip_name = chip_names.get(product_id, f"Unknown (0x{product_id:02X})")

    ok = product_id in (0x0A, 0x08, 0x06)  # any AD936x is valid
    return ok, {
        "product_id": product_id,
        "chip": chip_name,
        "revision": revision,
    }


def test_led_toggle(bus):
    """Toggle LEDs to provide visual confirmation."""
    try:
        # LedChaser exposes an 'out' CSR — write directly to override
        original = bus.regs.leds_out.read()
        # Blink pattern: all on, all off, restore
        bus.regs.leds_out.write(0x03)  # both LEDs on
        time.sleep(0.2)
        bus.regs.leds_out.write(0x00)  # both LEDs off
        time.sleep(0.2)
        bus.regs.leds_out.write(0x03)  # both LEDs on
        time.sleep(0.2)
        bus.regs.leds_out.write(original)  # restore
        return True, "LEDs toggled (check board visually)"
    except Exception as e:
        return False, str(e)


def test_pcie_dma_idle(bus):
    """Confirm DMA engine is present and idle (no stray enables)."""
    writer_en = bus.regs.pcie_dma0_writer_enable.read()
    reader_en = bus.regs.pcie_dma0_reader_enable.read()
    # Both should be 0 before we start anything
    ok = (writer_en == 0) and (reader_en == 0)
    return ok, {"writer_enable": writer_en, "reader_enable": reader_en}


def test_usb_ep3_bridge(bus):
    """
    Exercise the USB EP3 control-plane bridge (USBWishboneBridge) directly
    over raw USB bulk transfers — completely bypassing RemoteClient and
    litex_server. Cross-checks every read against the same register already
    read over `bus` in earlier steps, so this proves EP3 reaches the same
    live CSR bus, not just "a" response:

      1. READ32  identifier_mem[0]      vs. Step 2 (RemoteClient)
      2. READ32  dna_id (multi-word)    vs. Step 4 (RemoteClient)
      3. READ32  xadc_temperature       vs. Step 3 (RemoteClient)
      4. Full AD9364 SPI ping over EP3  vs. Step 6 (RemoteClient)
      5. WRITE32 leds_out (safe CSR)
      6. READ32  leds_out               verify the write landed
      7. READ32  to an unmapped address verify BUS_ERROR status, not a hang
    """
    dev = _usb_ep3_open()
    checks = {}
    all_ok = True
    try:
        # 1. SoC identifier — single word, first character(s).
        ident_addr = bus.mems.identifier_mem.base
        ep3_val = usb_ep3_read32(dev, ident_addr)
        ref_val = bus.read(ident_addr)
        ok = (ep3_val == ref_val)
        checks["identifier[0]"] = {"ok": ok, "ep3": f"0x{ep3_val:08x}", "ref": f"0x{ref_val:08x}"}
        all_ok &= ok

        # 2. DNA — multi-word CSR, reconstructed the same way RemoteClient does.
        ep3_dna = _usb_read_csr(dev, bus.regs.dna_id)
        ref_dna = bus.regs.dna_id.read()
        ok = (ep3_dna == ref_dna)
        checks["dna_id"] = {"ok": ok, "ep3": f"0x{ep3_dna:016x}", "ref": f"0x{ref_dna:016x}"}
        all_ok &= ok

        # 3. XADC temperature — live sensor, allow it to have ticked slightly
        #    between the two reads rather than requiring bit-exact equality.
        ep3_temp_raw = _usb_read_csr(dev, bus.regs.xadc_temperature)
        ref_temp_raw = bus.regs.xadc_temperature.read()
        ok = abs(ep3_temp_raw - ref_temp_raw) <= 8   # a few raw ADC counts of drift
        checks["xadc_temperature"] = {"ok": ok, "ep3": ep3_temp_raw, "ref": ref_temp_raw}
        all_ok &= ok

        # 4. AD9364 SPI product ID ping, entirely over EP3.
        spi_addrs = {
            "mosi":    bus.regs.ad9364_spi_mosi.addr,
            "control": bus.regs.ad9364_spi_control.addr,
            "status":  bus.regs.ad9364_spi_status.addr,
            "miso":    bus.regs.ad9364_spi_miso.addr,
        }
        try:
            ep3_chip_id = _usb_spi_read(dev, spi_addrs, 0x037)
            ok = (ep3_chip_id == 0x0A)
            checks["ad9364_product_id"] = {"ok": ok, "ep3": f"0x{ep3_chip_id:02x}", "expected": "0x0a"}
        except TimeoutError as e:
            checks["ad9364_product_id"] = {"ok": False, "error": str(e)}
            ok = False
        all_ok &= ok

        # 5/6. WRITE32 + READ32 round-trip on a safe, writable CSR.
        leds_addr = bus.regs.leds_out.addr
        original_leds = usb_ep3_read32(dev, leds_addr)
        test_pattern = (~original_leds) & 0x3
        usb_ep3_write32(dev, leds_addr, test_pattern)
        readback = usb_ep3_read32(dev, leds_addr)
        usb_ep3_write32(dev, leds_addr, original_leds)   # restore
        ok = (readback == test_pattern)
        checks["leds_out write/readback"] = {"ok": ok, "wrote": test_pattern, "read": readback}
        all_ok &= ok

        # 7. Unmapped address must come back BUS_ERROR, not hang or silently
        #    return garbage — proves the bridge's watchdog actually works.
        UNMAPPED_ADDR = 0x00020000   # past the 64KB CSR region, no slave decode
        status, _ = _usb_ep3_transact(dev, USB_OP_READ32, UNMAPPED_ADDR)
        ok = (status == USB_STATUS_BUS_ERROR)
        checks["unmapped address -> BUS_ERROR"] = {
            "ok": ok, "status": USB_STATUS_NAMES.get(status, hex(status)),
        }
        all_ok &= ok

    finally:
        _usb_ep3_close(dev)

    return all_ok, checks


# ──────────────────────────────────────────────────────────────────────────────
# Main
# ──────────────────────────────────────────────────────────────────────────────

def banner():
    print()
    print(HEAD("╔══════════════════════════════════════════════════╗"))
    print(HEAD("║         Spectra SDR — Hardware Validation          ║"))
    print(HEAD("╚══════════════════════════════════════════════════╝"))
    print()


def result_line(label, ok, detail=""):
    status = PASS("PASS") if ok else FAIL("FAIL")
    detail_str = f"  {detail}" if detail else ""
    print(f"  [{status}]  {label}{detail_str}")


def main():
    banner()

    parser = argparse.ArgumentParser(
        description="Spectra SDR hardware validation script",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--transport", choices=["pcie", "jtag"], default="pcie",
        help="How to reach the LiteX CSR bridge (default: pcie). "
             "Use 'jtag' if you haven't loaded the kernel driver yet.",
    )
    parser.add_argument(
        "--csr-csv", default=None,
        help="Path to csr.csv (default: auto-detect from build directory).",
    )
    parser.add_argument(
        "--host", default="localhost",
        help="litex_server host (default: localhost).",
    )
    parser.add_argument(
        "--port", default=1234, type=int,
        help="litex_server port (default: 1234).",
    )
    parser.add_argument(
        "--skip-reset", action="store_true",
        help="Skip the AD9364 reset cycle (useful if RFIC is already initialised).",
    )
    args = parser.parse_args()

    # ── Locate csr.csv ─────────────────────────────────────────────────────
    if args.csr_csv:
        csr_csv = args.csr_csv
    else:
        # Default: look next to this script, then in the build tree.
        script_dir = os.path.dirname(os.path.abspath(__file__))
        candidates = [
            os.path.join(script_dir, "csr.csv"),
            os.path.join(script_dir, "build", "spectra_platform", "csr.csv"),
        ]
        csr_csv = next((p for p in candidates if os.path.exists(p)), None)
        if csr_csv is None:
            print(FAIL("ERROR") + " Cannot find csr.csv. Pass --csr-csv <path>.")
            sys.exit(1)

    print(BOLD("Configuration"))
    print(f"  Transport : {args.transport.upper()}")
    print(f"  CSR CSV   : {csr_csv}")
    print()

    failures = []

    # ── Step 1: Interface detection (PCIe + USB) ───────────────────────────
    print(BOLD("Step 1 — Interface detection"))

    # PCIe bus check
    pcie_bus_ok, pcie_bus_info = detect_pcie_bus()
    if pcie_bus_ok:
        result_line("PCIe bus", True, pcie_bus_info)
    elif pcie_bus_ok is None:
        print(f"  [----]  PCIe bus  (lspci not available)")
    else:
        result_line("PCIe bus", False, "Xilinx device not found on PCIe bus")

    # PCIe device node check
    if args.transport == "pcie":
        pcie_dev_ok, pcie_dev_node = check_pcie_device()
        if pcie_dev_ok:
            result_line("PCIe driver", True, pcie_dev_node)
        else:
            result_line("PCIe driver", False, "no /dev/spectra0 — load kernel module")
            failures.append("PCIe device node missing")
    else:
        print(f"  [----]  PCIe driver  (skipped, transport=jtag)")

    # USB device check
    usb_ok, usb_info = detect_usb_device()
    if usb_ok:
        result_line("USB device", True, usb_info)
    elif usb_ok is None:
        print(f"  [----]  USB device  (lsusb/pyusb not available)")
    else:
        print(f"  [ -- ]  USB device  not detected (optional if using PCIe)")

    # Summary line
    has_pcie = pcie_bus_ok is True
    has_usb = usb_ok is True
    if has_pcie and has_usb:
        print(f"\n  {PASS('>>>')} Both PCIe and USB detected — PCIe will be used (Gen2 x2, ~8 Gbps)")
    elif has_pcie:
        print(f"\n  {PASS('>>>')} PCIe detected (Gen2 x2, ~8 Gbps)")
    elif has_usb:
        print(f"\n  {PASS('>>>')} USB detected (HS, ~480 Mbps)")
    else:
        if args.transport != "jtag":
            print(f"\n  {WARN('>>>')} No PCIe or USB detected — check board seating")
    print()

    # ── Connect RemoteClient ───────────────────────────────────────────────
    print(BOLD("Connecting to LiteX CSR bridge …"))
    try:
        from litex import RemoteClient
        bus = RemoteClient(host=args.host, port=args.port, csr_csv=csr_csv)
        bus.open()
        print(f"  Connected  ({args.host}:{args.port})")
    except Exception as e:
        print(FAIL(f"  FAIL — cannot connect: {e}"))
        if args.transport == "jtag":
            print("  Hint: run  litex_server --jtag --jtag-config openocd_xc7_ft2232.cfg  first.")
        else:
            print("  Hint: run  litex_server --pcie  (or use --transport jtag for JTAG access).")
        sys.exit(1)
    print()

    # ── Step 2: SoC identification ──────────────────────────────────────────
    print(BOLD("Step 2 — SoC identification"))
    try:
        ok, ident = test_soc_ident(bus)
        result_line("SoC ident string", ok, ident if ok else "empty or unreadable")
        if not ok:
            failures.append("SoC ident string empty")
    except Exception as e:
        result_line("SoC ident", False, str(e))
        failures.append(f"SoC ident error: {e}")
    print()

    # ── Step 3: XADC — FPGA temperature and voltages ──────────────────────
    print(BOLD("Step 3 — FPGA health (XADC)"))
    try:
        ok, xadc = test_xadc(bus)
        result_line("Temperature in range (0–85 °C)",    0 < xadc["temp_c"] < 85,
                    f"{xadc['temp_c']:.1f} °C")
        result_line("VCCINT  nominal 1.0 V  (±8%)",      0.92 < xadc["vccint_v"]  < 1.08,
                    f"{xadc['vccint_v']:.3f} V")
        result_line("VCCAUX  nominal 1.8 V  (±6%)",      1.70 < xadc["vccaux_v"]  < 1.90,
                    f"{xadc['vccaux_v']:.3f} V")
        result_line("VCCBRAM nominal 1.0 V  (±8%)",      0.92 < xadc["vccbram_v"] < 1.08,
                    f"{xadc['vccbram_v']:.3f} V")
        if not ok:
            failures.append("XADC readings out of range")
    except Exception as e:
        result_line("XADC read", False, str(e))
        failures.append(f"XADC error: {e}")
    print()

    # ── Step 4: DNA — unique device serial ────────────────────────────────
    print(BOLD("Step 4 — Device DNA (unique serial)"))
    try:
        ok, dna = test_dna(bus)
        dna_str = f"0x{dna:016X}"
        is_nonzero = dna != 0
        result_line("DNA ID readable and non-zero", is_nonzero, dna_str)
        if not is_nonzero:
            failures.append("DNA ID read as zero")
    except Exception as e:
        result_line("DNA read", False, str(e))
        failures.append(f"DNA error: {e}")
    print()

    # ── Step 5: HyperRAM ────────────────────────────────────────────────────
    print(BOLD("Step 5 — HyperRAM (8 MB)"))
    try:
        ok, ram_results = test_hyperram(bus)
        for name, info in ram_results.items():
            result_line(f"{name} pattern ({info['words']} words)", info["ok"],
                        f"{info['mismatches']} mismatches" if not info["ok"] else "OK")
        if not ok:
            failures.append("HyperRAM read/write failed")
    except Exception as e:
        result_line("HyperRAM test", False, str(e))
        failures.append(f"HyperRAM error: {e}")
    print()

    # ── Step 6: AD9364 reset + product ID ─────────────────────────────────
    print(BOLD("Step 6 — AD9364 RFIC (SPI ping)"))
    try:
        if args.skip_reset:
            ok, info = test_ad9364_spi(bus)
            label = "Product ID (0x037 → 0x0A), no reset"
        else:
            ok, info = test_ad9364_reset_cycle(bus)
            label = "Product ID (0x037 → 0x0A), after reset"

        if info.get("chip_id") is not None:
            detail = f"got 0x{info['chip_id']:02X}, expected 0x{info['expected']:02X}"
        else:
            detail = info.get("error", "")
        result_line(label, ok, detail)
        if not ok:
            failures.append("AD9364 SPI ping failed")
    except Exception as e:
        result_line("AD9364 SPI", False, str(e))
        failures.append(f"AD9364 error: {e}")
    print()

    # ── Step 7: AD9364 chip identification ───────────────────────────────
    print(BOLD("Step 7 — AD9364 chip identification"))
    try:
        ok, rev_info = test_ad9364_revision(bus)
        if "error" not in rev_info:
            result_line("Chip variant", ok,
                        f"{rev_info['chip']} (ID=0x{rev_info['product_id']:02X}, rev=0x{rev_info['revision']:02X})")
        else:
            result_line("Chip identification", False, rev_info["error"])
        if not ok:
            failures.append("AD9364 chip identification failed")
    except Exception as e:
        result_line("AD9364 revision", False, str(e))
        failures.append(f"AD9364 revision error: {e}")
    print()

    # ── Step 8: AD9364 SPI bus integrity ──────────────────────────────────
    print(BOLD("Step 8 — AD9364 SPI loopback (scratch register)"))
    try:
        ok, spi_results = test_ad9364_spi_loopback(bus)
        passed = sum(1 for r in spi_results if r["ok"])
        total = len(spi_results)
        result_line(f"SPI write/readback ({passed}/{total} patterns)", ok,
                    "all matched" if ok else "mismatch detected")
        if not ok:
            for r in spi_results:
                if not r["ok"]:
                    detail = f"wrote 0x{r['wrote']:02X}, read 0x{r['read']:02X}" if r["read"] is not None else r.get("error", "")
                    print(f"           {FAIL('MISMATCH')}  {detail}")
            failures.append("AD9364 SPI loopback failed")
    except Exception as e:
        result_line("SPI loopback", False, str(e))
        failures.append(f"SPI loopback error: {e}")
    print()

    # ── Step 9: LED toggle ────────────────────────────────────────────────
    print(BOLD("Step 9 — LED toggle (visual check)"))
    try:
        ok, led_detail = test_led_toggle(bus)
        result_line("LED blink", ok, led_detail)
        if not ok:
            failures.append(f"LED toggle failed: {led_detail}")
    except Exception as e:
        result_line("LED toggle", False, str(e))
        failures.append(f"LED error: {e}")
    print()

    # ── Step 10: PCIe DMA (PCIe transport only) ───────────────────────────
    if args.transport == "pcie":
        print(BOLD("Step 10 — PCIe DMA engine"))
        try:
            ok, dma = test_pcie_dma_idle(bus)
            result_line("DMA writer idle (enable=0)", dma["writer_enable"] == 0,
                        f"writer_enable={dma['writer_enable']}")
            result_line("DMA reader idle (enable=0)", dma["reader_enable"] == 0,
                        f"reader_enable={dma['reader_enable']}")
            if not ok:
                failures.append("DMA not idle — unexpected state")
        except Exception as e:
            result_line("PCIe DMA read", False, str(e))
            failures.append(f"DMA error: {e}")
        print()
    else:
        print(BOLD("Step 10 — PCIe DMA engine"))
        print("  [----]  Skipped (transport=jtag)")
        print()

    # ── Step 11: USB EP3 control-plane bridge (independent of --transport) ─
    print(BOLD("Step 11 — USB EP3 control bridge"))
    if not has_usb:
        print("  [----]  Skipped (no USB device detected)")
    else:
        try:
            import usb.core  # noqa: F401  (just probing availability)
        except ImportError:
            print("  [----]  Skipped (pyusb not installed — pip install pyusb)")
        else:
            try:
                ok, checks = test_usb_ep3_bridge(bus)
                for name, info in checks.items():
                    if "error" in info:
                        result_line(name, False, info["error"])
                    elif "status" in info:
                        result_line(name, info["ok"], f"status={info['status']}")
                    else:
                        detail = ", ".join(f"{k}={v}" for k, v in info.items() if k != "ok")
                        result_line(name, info["ok"], detail)
                if not ok:
                    failures.append("USB EP3 control bridge check(s) failed")
            except Exception as e:
                result_line("USB EP3 bridge", False, str(e))
                failures.append(f"USB EP3 error: {e}")
    print()

    bus.close()

    # ── Summary ────────────────────────────────────────────────────────────
    print(HEAD("══════════════════════════════════════════════════════"))
    if not failures:
        print(PASS("  ALL TESTS PASSED — your Spectra SDR is ready."))
    else:
        print(FAIL(f"  {len(failures)} TEST(S) FAILED:"))
        for f in failures:
            print(f"    • {f}")
    print(HEAD("══════════════════════════════════════════════════════"))
    print()

    sys.exit(0 if not failures else 1)


if __name__ == "__main__":
    main()
