#!/usr/bin/env python3
"""
Spectra SDR — Customer Validation Script
=============================================
Run this after loading the bitstream to verify your SDR is working correctly.

Usage:
  # Via PCIe (after loading litepcie driver):
  sudo python3 validate_sdr.py

  # Via JTAG (no driver needed — requires openocd + litex_server running):
  litex_server --jtag --jtag-config openocd_xc7_ft2232.cfg &
  python3 validate_sdr.py --transport jtag

Requirements:
  pip install litex

The bitstream ships a LiteX CSR bridge. The script reads:
  - FPGA temperature and supply voltages (XADC)
  - Unique device DNA serial number
  - AD9364 product ID via SPI (confirms RFIC is alive)
  - PCIe DMA status (PCIe transport only)
"""

import os
import sys
import time
import argparse

# ──────────────────────────────────────────────────────────────────────────────
# Colour helpers
# ──────────────────────────────────────────────────────────────────────────────

def _colour(code, text):
    if sys.stdout.isatty():
        return f"\033[{code}m{text}\033[0m"
    return text

PASS  = lambda t: _colour("32;1", t)
FAIL  = lambda t: _colour("31;1", t)
WARN  = lambda t: _colour("33;1", t)
HEAD  = lambda t: _colour("36;1", t)
BOLD  = lambda t: _colour("1",    t)

# ──────────────────────────────────────────────────────────────────────────────
# SPI helpers  (uses ad9364_spi_* CSRs generated by LiteX)
# ──────────────────────────────────────────────────────────────────────────────

# AD9364 SPI frame (24-bit):
#  [23]    R/~W  — 1 = read
#  [22:21] W[1:0] — 00 = 1-byte transfer
#  [20:8]  Address (13-bit, but AD9364 uses bits 12:0)
#  [7:0]   Data (ignored on read, written on write)

def _spi_read(bus, addr):
    """Perform a 24-bit SPI read of the AD9364 register at `addr`."""
    mosi_val = (1 << 23) | (addr << 8)          # R=1, W[1:0]=00, addr, data=0
    bus.regs.ad9364_spi_mosi.write(mosi_val)
    bus.regs.ad9364_spi_control.write((24 << 8) | 1)  # length=24, start=1
    timeout = time.time() + 0.1
    while not (bus.regs.ad9364_spi_status.read() & 1):
        if time.time() > timeout:
            raise TimeoutError("SPI transfer timed out")
        time.sleep(0.001)
    return bus.regs.ad9364_spi_miso.read() & 0xFF


def _spi_write(bus, addr, data):
    """Perform a 24-bit SPI write of `data` to the AD9364 register at `addr`."""
    mosi_val = (0 << 23) | (addr << 8) | (data & 0xFF)  # R=0
    bus.regs.ad9364_spi_mosi.write(mosi_val)
    bus.regs.ad9364_spi_control.write((24 << 8) | 1)
    timeout = time.time() + 0.1
    while not (bus.regs.ad9364_spi_status.read() & 1):
        if time.time() > timeout:
            raise TimeoutError("SPI transfer timed out")
        time.sleep(0.001)

# ──────────────────────────────────────────────────────────────────────────────
# Individual test functions
# ──────────────────────────────────────────────────────────────────────────────

def check_pcie_device():
    """Check that the PCIe device node exists (driver loaded)."""
    node = "/dev/litepcie0"
    exists = os.path.exists(node)
    return exists, node


def test_xadc(bus):
    """Read FPGA internal sensors via XADC."""
    raw_temp   = bus.regs.xadc_temperature.read()
    raw_vccint = bus.regs.xadc_vccint.read()
    raw_vccaux = bus.regs.xadc_vccaux.read()
    raw_vccbram= bus.regs.xadc_vccbram.read()

    temp    = raw_temp   * 503.975 / 4096 - 273.15
    vccint  = raw_vccint  * 3 / 4096
    vccaux  = raw_vccaux  * 3 / 4096
    vccbram = raw_vccbram * 3 / 4096

    results = {
        "temp_c":   temp,
        "vccint_v": vccint,
        "vccaux_v": vccaux,
        "vccbram_v":vccbram,
    }

    # Sanity bounds
    ok = (
        0 < temp < 85 and
        0.92 < vccint  < 1.08 and   # nominal 1.0V ±8%
        1.70 < vccaux  < 1.90 and   # nominal 1.8V ±6%
        0.92 < vccbram < 1.08       # nominal 1.0V ±8%
    )
    return ok, results


def test_dna(bus):
    """Read the unique FPGA DNA identifier."""
    dna_hi = bus.regs.dna_id.read()   # LiteX packs 64-bit as two 32-bit regs
    # RemoteClient automatically handles multi-word: returns 64-bit int
    dna = dna_hi
    return True, dna


def test_ad9364_spi(bus):
    """Ping the AD9364 RFIC by reading its Product ID register (0x037 → 0x0A)."""
    PRODUCT_ID_REG = 0x037
    EXPECTED_ID    = 0x0A   # AD9364 product ID

    try:
        chip_id = _spi_read(bus, PRODUCT_ID_REG)
    except TimeoutError as e:
        return False, {"error": str(e), "chip_id": None}

    ok = (chip_id == EXPECTED_ID)
    return ok, {"chip_id": chip_id, "expected": EXPECTED_ID}


def test_ad9364_reset_cycle(bus):
    """Assert and deassert AD9364 reset, then re-read product ID."""
    # PHY control bit 0 = rst_n (active-low reset).
    bus.regs.ad9364_phy_control.write(0x00)   # assert reset (rst_n=0)
    time.sleep(0.01)
    bus.regs.ad9364_phy_control.write(0x01)   # deassert reset (rst_n=1)
    time.sleep(0.05)                           # wait for RFIC boot

    ok, info = test_ad9364_spi(bus)
    return ok, info


def test_pcie_dma_idle(bus):
    """Confirm DMA engine is present and idle (no stray enables)."""
    writer_en = bus.regs.pcie_dma0_writer_enable.read()
    reader_en = bus.regs.pcie_dma0_reader_enable.read()
    # Both should be 0 before we start anything
    ok = (writer_en == 0) and (reader_en == 0)
    return ok, {"writer_enable": writer_en, "reader_enable": reader_en}


# ──────────────────────────────────────────────────────────────────────────────
# Main
# ──────────────────────────────────────────────────────────────────────────────

def banner():
    print()
    print(HEAD("╔══════════════════════════════════════════════════╗"))
    print(HEAD("║         Spectra SDR — Hardware Validation          ║"))
    print(HEAD("╚══════════════════════════════════════════════════╝"))
    print()


def result_line(label, ok, detail=""):
    status = PASS("PASS") if ok else FAIL("FAIL")
    detail_str = f"  {detail}" if detail else ""
    print(f"  [{status}]  {label}{detail_str}")


def main():
    banner()

    parser = argparse.ArgumentParser(
        description="Spectra SDR hardware validation script",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--transport", choices=["pcie", "jtag"], default="pcie",
        help="How to reach the LiteX CSR bridge (default: pcie). "
             "Use 'jtag' if you haven't loaded the kernel driver yet.",
    )
    parser.add_argument(
        "--csr-csv", default=None,
        help="Path to csr.csv (default: auto-detect from build directory).",
    )
    parser.add_argument(
        "--host", default="localhost",
        help="litex_server host (default: localhost).",
    )
    parser.add_argument(
        "--port", default=1234, type=int,
        help="litex_server port (default: 1234).",
    )
    parser.add_argument(
        "--skip-reset", action="store_true",
        help="Skip the AD9364 reset cycle (useful if RFIC is already initialised).",
    )
    args = parser.parse_args()

    # ── Locate csr.csv ─────────────────────────────────────────────────────
    if args.csr_csv:
        csr_csv = args.csr_csv
    else:
        # Default: look next to this script, then in the build tree.
        script_dir = os.path.dirname(os.path.abspath(__file__))
        candidates = [
            os.path.join(script_dir, "csr.csv"),
            os.path.join(script_dir, "build", "spectra_platform", "csr.csv"),
        ]
        csr_csv = next((p for p in candidates if os.path.exists(p)), None)
        if csr_csv is None:
            print(FAIL("ERROR") + " Cannot find csr.csv. Pass --csr-csv <path>.")
            sys.exit(1)

    print(BOLD("Configuration"))
    print(f"  Transport : {args.transport.upper()}")
    print(f"  CSR CSV   : {csr_csv}")
    print()

    failures = []

    # ── Step 1: PCIe device node (PCIe transport only) ─────────────────────
    if args.transport == "pcie":
        print(BOLD("Step 1 — PCIe enumeration"))
        ok, node = check_pcie_device()
        result_line("/dev/litepcie0 present", ok, node if ok else "not found — load the litepcie driver")
        if not ok:
            failures.append("PCIe device node missing")
        print()
    else:
        print(BOLD("Step 1 — PCIe enumeration"))
        print(f"  [----]  Skipped (transport=jtag)")
        print()

    # ── Connect RemoteClient ───────────────────────────────────────────────
    print(BOLD("Connecting to LiteX CSR bridge …"))
    try:
        from litex import RemoteClient
        bus = RemoteClient(host=args.host, port=args.port, csr_csv=csr_csv)
        bus.open()
        print(f"  Connected  ({args.host}:{args.port})")
    except Exception as e:
        print(FAIL(f"  FAIL — cannot connect: {e}"))
        if args.transport == "jtag":
            print("  Hint: run  litex_server --jtag --jtag-config openocd_xc7_ft2232.cfg  first.")
        else:
            print("  Hint: run  litex_server --pcie  (or use --transport jtag for JTAG access).")
        sys.exit(1)
    print()

    # ── Step 2: XADC — FPGA temperature and voltages ──────────────────────
    print(BOLD("Step 2 — FPGA health (XADC)"))
    try:
        ok, xadc = test_xadc(bus)
        result_line("Temperature in range (0–85 °C)",    0 < xadc["temp_c"] < 85,
                    f"{xadc['temp_c']:.1f} °C")
        result_line("VCCINT  nominal 1.0 V  (±8%)",      0.92 < xadc["vccint_v"]  < 1.08,
                    f"{xadc['vccint_v']:.3f} V")
        result_line("VCCAUX  nominal 1.8 V  (±6%)",      1.70 < xadc["vccaux_v"]  < 1.90,
                    f"{xadc['vccaux_v']:.3f} V")
        result_line("VCCBRAM nominal 1.0 V  (±8%)",      0.92 < xadc["vccbram_v"] < 1.08,
                    f"{xadc['vccbram_v']:.3f} V")
        if not ok:
            failures.append("XADC readings out of range")
    except Exception as e:
        result_line("XADC read", False, str(e))
        failures.append(f"XADC error: {e}")
    print()

    # ── Step 3: DNA — unique device serial ────────────────────────────────
    print(BOLD("Step 3 — Device DNA (unique serial)"))
    try:
        ok, dna = test_dna(bus)
        dna_str = f"0x{dna:016X}"
        is_nonzero = dna != 0
        result_line("DNA ID readable and non-zero", is_nonzero, dna_str)
        if not is_nonzero:
            failures.append("DNA ID read as zero")
    except Exception as e:
        result_line("DNA read", False, str(e))
        failures.append(f"DNA error: {e}")
    print()

    # ── Step 4: AD9364 reset + product ID ─────────────────────────────────
    print(BOLD("Step 4 — AD9364 RFIC (SPI ping)"))
    try:
        if args.skip_reset:
            ok, info = test_ad9364_spi(bus)
            label = "Product ID (0x037 → 0x0A), no reset"
        else:
            ok, info = test_ad9364_reset_cycle(bus)
            label = "Product ID (0x037 → 0x0A), after reset"

        if info.get("chip_id") is not None:
            detail = f"got 0x{info['chip_id']:02X}, expected 0x{info['expected']:02X}"
        else:
            detail = info.get("error", "")
        result_line(label, ok, detail)
        if not ok:
            failures.append("AD9364 SPI ping failed")
    except Exception as e:
        result_line("AD9364 SPI", False, str(e))
        failures.append(f"AD9364 error: {e}")
    print()

    # ── Step 5: PCIe DMA (PCIe transport only) ────────────────────────────
    if args.transport == "pcie":
        print(BOLD("Step 5 — PCIe DMA engine"))
        try:
            ok, dma = test_pcie_dma_idle(bus)
            result_line("DMA writer idle (enable=0)", dma["writer_enable"] == 0,
                        f"writer_enable={dma['writer_enable']}")
            result_line("DMA reader idle (enable=0)", dma["reader_enable"] == 0,
                        f"reader_enable={dma['reader_enable']}")
            if not ok:
                failures.append("DMA not idle — unexpected state")
        except Exception as e:
            result_line("PCIe DMA read", False, str(e))
            failures.append(f"DMA error: {e}")
        print()
    else:
        print(BOLD("Step 5 — PCIe DMA engine"))
        print("  [----]  Skipped (transport=jtag)")
        print()

    bus.close()

    # ── Summary ────────────────────────────────────────────────────────────
    print(HEAD("══════════════════════════════════════════════════════"))
    if not failures:
        print(PASS("  ALL TESTS PASSED — your Spectra SDR is ready."))
    else:
        print(FAIL(f"  {len(failures)} TEST(S) FAILED:"))
        for f in failures:
            print(f"    • {f}")
    print(HEAD("══════════════════════════════════════════════════════"))
    print()

    sys.exit(0 if not failures else 1)


if __name__ == "__main__":
    main()
